### ISSUE TITLE
Yarn and dev issues

### ISSUE THREAD

**Issue by gichiba** [ethereum/fellowship-program-website#87]
Still troubleshooting but when I try to run `yarn dev` I get this error: 

```
yarn run v1.22.22
$ next dev
/home/mgkbr/Documents/ef/nxbn-azorius/fellowship-program-website/node_modules/next/dist/lib/picocolors.js:134
const { env, stdout } = ((_globalThis = globalThis) == null ? void 0 : _globalThis.process) ?? {};
                                                                                             ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module.mod.require (/home/mgkbr/Documents/ef/nxbn-azorius/fellowship-program-website/node_modules/next/dist/server/require-hook.js:65:28)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/mgkbr/Documents/ef/nxbn-azorius/fellowship-program-website/node_modules/next/dist/build/output/log.js:55:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by corwintines** [comment]
Sounds like you got this resolved right @gichiba? If not, lets sync on this, feel free to put something on my calendar.

**Comment by gichiba** [comment]
Yep it's fixed!
